### ISSUE TITLE
Older version IntuneWin32App Module

### ISSUE THREAD

**Issue by GertonD** [Romanitho/WingetIntunePackager#19] opened 2023-10-20 13:48 UTC
I had an older version IntuneWin32App Module already installed on my machine which resulted in not being able to connect to tenants.
I solved it by manually running the module install command with the addition of -AllowClobber.

**Comment by Romanitho** [comment] 2023-10-20 14:29
this is caused by multiple versions of IntuneWin32App ?

**Comment by GertonD** [comment] 2023-10-23 05:34
The version I had previously installed did not contain the function Connect-MSIntuneGraph which was added in version 1.2.0.

**Comment by GertonD** [comment] 2023-10-25 05:07
Yes, you could builtin a version check but I doubt there will be a lot of people having this old version installed and if they have they could reference this closed issue.

**Comment by Romanitho** [comment] 2023-10-25 05:26
It's a good idea. If you have an idea, feel free to implement the code to get credited 👌🏼

**Comment by Romanitho** [comment] 2023-11-20 13:42
Should be fixed #25

**Closed by Romanitho** 2023-11-20 13:42 UTC
